const countriesFr = {
    Afrique: [
        { code: 'DZ', name: 'Algérie' },
        { code: 'AO', name: 'Angola' },
        { code: 'BJ', name: 'Bénin' },
        { code: 'BW', name: 'Botswana' },
        { code: 'BF', name: 'Burkina Faso' },
        { code: 'BI', name: 'Burundi' },
        { code: 'CV', name: 'Cap-Vert' },
        { code: 'CM', name: 'Cameroun' },
        { code: 'CF', name: 'République centrafricaine' },
        { code: 'TD', name: 'Tchad' },
        { code: 'KM', name: 'Comores' },
        { code: 'CD', name: 'République démocratique du Congo' },
        { code: 'DJ', name: 'Djibouti' },
        { code: 'EG', name: 'Égypte' },
        { code: 'GQ', name: 'Guinée équatoriale' },
        { code: 'ER', name: 'Érythrée' },
        { code: 'SZ', name: 'Eswatini' },
        { code: 'ET', name: 'Éthiopie' },
        { code: 'GA', name: 'Gabon' },
        { code: 'GM', name: 'Gambie' },
        { code: 'GH', name: 'Ghana' },
        { code: 'GN', name: 'Guinée' },
        { code: 'GW', name: 'Guinée-Bissau' },
        { code: 'CI', name: "Côte d'Ivoire" },
        { code: 'KE', name: 'Kenya' },
        { code: 'LS', name: 'Lesotho' },
        { code: 'LR', name: 'Libéria' },
        { code: 'LY', name: 'Libye' },
        { code: 'MG', name: 'Madagascar' },
        { code: 'MW', name: 'Malawi' },
        { code: 'ML', name: 'Mali' },
        { code: 'MR', name: 'Mauritanie' },
        { code: 'MU', name: 'Maurice' },
        { code: 'MA', name: 'Maroc' },
        { code: 'MZ', name: 'Mozambique' },
        { code: 'NA', name: 'Namibie' },
        { code: 'NE', name: 'Niger' },
        { code: 'NG', name: 'Nigéria' },
        { code: 'CG', name: 'République du Congo' },
        { code: 'RW', name: 'Rwanda' },
        { code: 'ST', name: 'Sao Tomé-et-Principe' },
        { code: 'SN', name: 'Sénégal' },
        { code: 'SC', name: 'Seychelles' },
        { code: 'SL', name: 'Sierra Leone' },
        { code: 'SO', name: 'Somalie' },
        { code: 'ZA', name: 'Afrique du Sud' },
        { code: 'SS', name: 'Soudan du Sud' },
        { code: 'SD', name: 'Soudan' },
        { code: 'TZ', name: 'Tanzanie' },
        { code: 'TG', name: 'Togo' },
        { code: 'TN', name: 'Tunisie' },
        { code: 'UG', name: 'Ouganda' },
        { code: 'ZM', name: 'Zambie' },
        { code: 'ZW', name: 'Zimbabwe' },
    ],
    Amérique: [
        { code: 'AG', name: 'Antigua-et-Barbuda' },
        { code: 'AR', name: 'Argentine' },
        { code: 'BS', name: 'Bahamas' },
        { code: 'BB', name: 'Barbade' },
        { code: 'BZ', name: 'Belize' },
        { code: 'BO', name: 'Bolivie' },
        { code: 'BR', name: 'Brésil' },
        { code: 'CA', name: 'Canada' },
        { code: 'CL', name: 'Chili' },
        { code: 'CO', name: 'Colombie' },
        { code: 'CR', name: 'Costa Rica' },
        { code: 'CU', name: 'Cuba' },
        { code: 'DM', name: 'Dominique' },
        { code: 'DO', name: 'République dominicaine' },
        { code: 'EC', name: 'Équateur' },
        { code: 'SV', name: 'Salvador' },
        { code: 'GD', name: 'Grenade' },
        { code: 'GT', name: 'Guatemala' },
        { code: 'GY', name: 'Guyana' },
        { code: 'HT', name: 'Haïti' },
        { code: 'HN', name: 'Honduras' },
        { code: 'JM', name: 'Jamaïque' },
        { code: 'MX', name: 'Mexique' },
        { code: 'NI', name: 'Nicaragua' },
        { code: 'PA', name: 'Panama' },
        { code: 'PY', name: 'Paraguay' },
        { code: 'PE', name: 'Pérou' },
        { code: 'KN', name: 'Saint-Christophe-et-Niévès' },
        { code: 'LC', name: 'Sainte-Lucie' },
        { code: 'VC', name: 'Saint-Vincent-et-les-Grenadines' },
        { code: 'SR', name: 'Suriname' },
        { code: 'TT', name: 'Trinité-et-Tobago' },
        { code: 'US', name: 'États-Unis' },
        { code: 'UY', name: 'Uruguay' },
        { code: 'VE', name: 'Venezuela' },
    ],
    Asie: [
        { code: 'AF', name: 'Afghanistan' },
        { code: 'AM', name: 'Arménie' },
        { code: 'AZ', name: 'Azerbaïdjan' },
        { code: 'BH', name: 'Bahreïn' },
        { code: 'BD', name: 'Bangladesh' },
        { code: 'BT', name: 'Bhoutan' },
        { code: 'BN', name: 'Brunei' },
        { code: 'KH', name: 'Cambodge' },
        { code: 'CN', name: 'Chine' },
        { code: 'CY', name: 'Chypre' },
        { code: 'GE', name: 'Géorgie' },
        { code: 'IN', name: 'Inde' },
        { code: 'ID', name: 'Indonésie' },
        { code: 'IR', name: 'Iran' },
        { code: 'IQ', name: 'Irak' },
        { code: 'IL', name: 'Israël' },
        { code: 'JP', name: 'Japon' },
        { code: 'JO', name: 'Jordanie' },
        { code: 'KZ', name: 'Kazakhstan' },
        { code: 'KW', name: 'Koweït' },
        { code: 'KG', name: 'Kirghizistan' },
        { code: 'LA', name: 'Laos' },
        { code: 'LB', name: 'Liban' },
        { code: 'MY', name: 'Malaisie' },
        { code: 'MV', name: 'Maldives' },
        { code: 'MN', name: 'Mongolie' },
        { code: 'MM', name: 'Myanmar' },
        { code: 'NP', name: 'Népal' },
        { code: 'KP', name: 'Corée du Nord' },
        { code: 'OM', name: 'Oman' },
        { code: 'PK', name: 'Pakistan' },
        { code: 'PS', name: 'Palestine' },
        { code: 'PH', name: 'Philippines' },
        { code: 'QA', name: 'Qatar' },
        { code: 'SA', name: 'Arabie saoudite' },
        { code: 'SG', name: 'Singapour' },
        { code: 'KR', name: 'Corée du Sud' },
        { code: 'LK', name: 'Sri Lanka' },
        { code: 'SY', name: 'Syrie' },
        { code: 'TJ', name: 'Tadjikistan' },
        { code: 'TH', name: 'Thaïlande' },
        { code: 'TL', name: 'Timor oriental' },
        { code: 'TR', name: 'Turquie' },
        { code: 'TM', name: 'Turkménistan' },
        { code: 'AE', name: 'Émirats arabes unis' },
        { code: 'UZ', name: 'Ouzbékistan' },
        { code: 'VN', name: 'Vietnam' },
        { code: 'YE', name: 'Yémen' },
    ],
    Europe: [
        { code: 'AL', name: 'Albanie' },
        { code: 'AD', name: 'Andorre' },
        { code: 'AT', name: 'Autriche' },
        { code: 'BY', name: 'Biélorussie' },
        { code: 'BE', name: 'Belgique' },
        { code: 'BA', name: 'Bosnie-Herzégovine' },
        { code: 'BG', name: 'Bulgarie' },
        { code: 'HR', name: 'Croatie' },
        { code: 'CY', name: 'Chypre' },
        { code: 'CZ', name: 'République tchèque' },
        { code: 'DK', name: 'Danemark' },
        { code: 'EE', name: 'Estonie' },
        { code: 'FI', name: 'Finlande' },
        { code: 'FR', name: 'France' },
        { code: 'DE', name: 'Allemagne' },
        { code: 'GR', name: 'Grèce' },
        { code: 'HU', name: 'Hongrie' },
        { code: 'IS', name: 'Islande' },
        { code: 'IE', name: 'Irlande' },
        { code: 'IT', name: 'Italie' },
        { code: 'LV', name: 'Lettonie' },
        { code: 'LI', name: 'Liechtenstein' },
        { code: 'LT', name: 'Lituanie' },
        { code: 'LU', name: 'Luxembourg' },
        { code: 'MT', name: 'Malte' },
        { code: 'MD', name: 'Moldavie' },
        { code: 'MC', name: 'Monaco' },
        { code: 'ME', name: 'Monténégro' },
        { code: 'NL', name: 'Pays-Bas' },
        { code: 'MK', name: 'Macédoine du Nord' },
        { code: 'NO', name: 'Norvège' },
        { code: 'PL', name: 'Pologne' },
        { code: 'PT', name: 'Portugal' },
        { code: 'RO', name: 'Roumanie' },
        { code: 'RU', name: 'Russie' },
        { code: 'SM', name: 'Saint-Marin' },
        { code: 'RS', name: 'Serbie' },
        { code: 'SK', name: 'Slovaquie' },
        { code: 'SI', name: 'Slovénie' },
        { code: 'ES', name: 'Espagne' },
        { code: 'SE', name: 'Suède' },
        { code: 'CH', name: 'Suisse' },
        { code: 'UA', name: 'Ukraine' },
        { code: 'GB', name: 'Royaume-Uni' },
    ],
    Océanie: [
        { code: 'AU', name: 'Australie' },
        { code: 'FJ', name: 'Fidji' },
        { code: 'KI', name: 'Kiribati' },
        { code: 'MH', name: 'Îles Marshall' },
        { code: 'FM', name: 'Micronésie' },
        { code: 'NR', name: 'Nauru' },
        { code: 'NZ', name: 'Nouvelle-Zélande' },
        { code: 'PW', name: 'Palaos' },
        { code: 'PG', name: 'Papouasie-Nouvelle-Guinée' },
        { code: 'WS', name: 'Samoa' },
        { code: 'SB', name: 'Îles Salomon' },
        { code: 'TO', name: 'Tonga' },
        { code: 'TV', name: 'Tuvalu' },
        { code: 'VU', name: 'Vanuatu' },
    ],
};

export default countriesFr;
